ARG VERSION=3.15
FROM alpine:$VERSION as builder 

ARG VERSION

RUN apk update && apk upgrade && apk  --update --no-cache add bash

RUN echo "Version $VERSION" > /message.txt

FROM alpine:$VERSION

WORKDIR /opt

COPY --from=builder /message.txt /opt/message.txt

CMD ["cat", "/opt/message.txt"]
